global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - 172.31.1.31:8080   # Kafka 1 - change IP for your use case
      - 172.31.17.32:8080  # Kafka 2
      - 172.31.33.33:8080  # Kafka 3
 - job_name: 'zookeeper'
   static_configs:
    - targets:
      - 172.31.9.21:7070   # zookeeer IP and Assign port on enviromnet section of systemd file


# This will setup on admin machine